name: test

on: 
    push: 
        branches: [ "main" ]

    pull_request: 
        branches: [ "main" ]
  
    workflow_dispatch:
        
jobs: 
    make_test:
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v4
            - run: make test
    